import './landing_login.cy'
// import './my_recipes.cy'
import './manage_labels.cy'
import './people_and_profile.cy'
import './messages.cy'
import './create_recipe.cy'
import './shopping_lists.cy'
import './meal_plans.cy'
import './download_install.cy'
import './contribute.cy'
import './settings.cy'
import './about.cy'
import './log_out.cy'
